exports.default = {
  ns_demo01: {
    entry: '../src4js/pc4ns/demo01/index.js',
    entry4single: '../src4js/pc4ns/demo01/single.js',
    entry4debug: '../src4js/pc4ns/demo01/debug.js',
    buildPath: '../spa/nonstandard/demo01',
    servedPath: '/spa/nonstandard/demo01/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo01',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo01',to: '../ecology/spa/nonstandard/demo01'}]
  },
  ns_demo02: {
    entry: '../src4js/pc4ns/demo02/index.js',
    entry4single: '../src4js/pc4ns/demo02/single.js',
    entry4debug: '../src4js/pc4ns/demo02/debug.js',
    buildPath: '../spa/nonstandard/demo02',
    servedPath: '/spa/nonstandard/demo02/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo02',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo02',to: '../ecology/spa/nonstandard/demo02'}]
  },
  ns_demo03: {
    entry: '../src4js/pc4ns/demo03/index.js',
    entry4single: '../src4js/pc4ns/demo03/single.js',
    entry4debug: '../src4js/pc4ns/demo03/debug.js',
    buildPath: '../spa/nonstandard/demo03',
    servedPath: '/spa/nonstandard/demo03/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo03',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo03',to: '../ecology/spa/nonstandard/demo03'}]
  },
  ns_demo04: {
    entry: '../src4js/pc4ns/demo04/index.js',
    entry4single: '../src4js/pc4ns/demo04/single.js',
    entry4debug: '../src4js/pc4ns/demo04/debug.js',
    buildPath: '../spa/nonstandard/demo04',
    servedPath: '/spa/nonstandard/demo04/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo04',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo04',to: '../ecology/spa/nonstandard/demo04'}]
  },
  ns_demo05: {
    entry: '../src4js/pc4ns/demo05/index.js',
    entry4single: '../src4js/pc4ns/demo05/single.js',
    entry4debug: '../src4js/pc4ns/demo05/debug.js',
    buildPath: '../spa/nonstandard/demo05',
    servedPath: '/spa/nonstandard/demo05/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo05',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo05',to: '../ecology/spa/nonstandard/demo05'}]
  },
  ns_demo06: {
    entry: '../src4js/pc4ns/demo06/index.js',
    entry4single: '../src4js/pc4ns/demo06/single.js',
    entry4debug: '../src4js/pc4ns/demo06/debug.js',
    buildPath: '../spa/nonstandard/demo06',
    servedPath: '/spa/nonstandard/demo06/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo06',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo06',to: '../ecology/spa/nonstandard/demo06'}]
  },
  ns_demo07: {
    entry: '../src4js/pc4ns/demo07/index.js',
    entry4single: '../src4js/pc4ns/demo07/single.js',
    entry4debug: '../src4js/pc4ns/demo07/debug.js',
    buildPath: '../spa/nonstandard/demo07',
    servedPath: '/spa/nonstandard/demo07/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo07',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo07',to: '../ecology/spa/nonstandard/demo07'}]
  },
  ns_demo08: {
    entry: '../src4js/pc4ns/demo08/index.js',
    entry4single: '../src4js/pc4ns/demo08/single.js',
    entry4debug: '../src4js/pc4ns/demo08/debug.js',
    buildPath: '../spa/nonstandard/demo08',
    servedPath: '/spa/nonstandard/demo08/',
    cssName: 'index.css',
    jsName: 'index.js',
    jsSingleName: 'index4single.js',
    htmlName: 'index.html',
    htmlTemplate: 'index.html',
    library: 'weansDemo08',
    libraryTarget: 'umd',
    copyFiles: [{from: '../spa/nonstandard/demo08',to: '../ecology/spa/nonstandard/demo08'}]
  },
}